=== kutegram/compilers/epoc32/tools/commdb-schema/93schema/contents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Contents.xsd
    XML Schema with the definitions of the
    Contents file for CommDB
    
    Copyright (c) 2003, Symbian Ltd.
    All Rights Reserved
-->
<xsd:schema elementFormDefault="qualified" targetNamespace="SymbianOS.Generic.Comms-Infras.CommDB"
      xmlns="SymbianOS.Generic.Comms-Infras.CommDB" xmlns:xlink="http://www.w3.org/1999/xlink" 
      xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <!--
          Include Symbian Primitive elements
      -->
      <xsd:include schemaLocation="PrimitiveTypes.xsd"/>
      <xsd:import namespace="http://www.w3.org/1999/xlink" schemaLocation="XLinkAttributes.xsd"/>
      <!-- 
          Definition of the Contents elements
      -->
      <xsd:element name="Contents">
            <xsd:complexType>
                  <xsd:sequence>
                        <xsd:element maxOccurs="1" minOccurs="1" ref="commdb"/>
                        <xsd:element maxOccurs="unbounded" minOccurs="1" ref="table"/>
                  </xsd:sequence>
            </xsd:complexType>
      </xsd:element>
      <!--
          Definition of the table element
      -->
      <xsd:element name="table">
            <xsd:complexType>
                  <xsd:attribute name="file"  type="Text" use="required"/>
                  <xsd:attribute name="name"  type="Text" use="required"/>
                  <xsd:attribute name="entry" type="Text" use="required"/>
                  <xsd:attribute name="enum"  type="Text" use="required"/>
            </xsd:complexType>
      </xsd:element>
      <!--
          Definition of the commdb element
      -->
      <xsd:element name="commdb">
            <xsd:complexType>
                  <xsd:attribute name="type"  type="Text" use="required"/>
            </xsd:complexType>
      </xsd:element>
</xsd:schema>

=== kutegram/compilers/epoc32/tools/commdb-schema/92schema/contents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Contents.xml
    XML file with the definitions of the XML Schema files to be used
    by the CommDB Editor in order to learn the structure of the CommDB
    tables

    Copyright (c) 2004, Symbian Ltd.
    All Rights Reserved
-->

<CommDB:Contents xmlns="SymbianOS.Generic.Comms-Infras.CommDB"
                 xmlns:CommDB="SymbianOS.Generic.Comms-Infras.CommDB"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                 xsi:schemaLocation="SymbianOS.Generic.Comms-Infras.CommDB Contents.xsd">
     
<commdb type="Symbian OS Version 9.2"/>
            
<table file="InformationTable.xsd"               name="InformationTable"              entry="Information"              enum="CommTypes.xsd"/>
<table file="NetworkTable.xsd"                   name="NetworkTable"                  entry="Network"                  enum="CommTypes.xsd"/>
<table file="IAPTable.xsd"                       name="IAPTable"                      entry="IAP"                      enum="CommTypes.xsd"/>
<table file="ModemBearerTable.xsd"               name="ModemBearerTable"              entry="ModemBearer"              enum="CommTypes.xsd"/>
<table file="LANBearerTable.xsd"                 name="LANBearerTable"                entry="LANBearer"                enum="CommTypes.xsd"/>
<table file="LANServiceTable.xsd"                name="LANServiceTable"               entry="LANService"               enum="CommTypes.xsd"/>
<table file="DialInISPTable.xsd"                 name="DialInISPTable"                entry="DialInISP"                enum="CommTypes.xsd"/>
<table file="DialOutISPTable.xsd"                name="DialOutISPTable"               entry="DialOutISP"               enum="CommTypes.xsd"/>
<table file="AgentLookupTable.xsd"               name="AgentLookupTable"              entry="AgentLookup"              enum="CommTypes.xsd"/>
<table file="CDMA2000PacketServiceTable.xsd"     name="CDMA2000PacketServiceTable"    entry="CDMA2000PacketService"    enum="CommTypes.xsd"/>
<table file="DefaultCDMA2000Table.xsd"           name="DefaultCDMA2000Table"          entry="DefaultCDMA2000"          enum="CommTypes.xsd"/>
<table file="ChargecardTable.xsd"                name="ChargecardTable"               entry="Chargecard"               enum="CommTypes.xsd"/>
<table file="ConnectionPreferencesTable.xsd"     name="ConnectionPreferencesTable"    entry="ConnectionPreferences"    enum="CommTypes.xsd"/>
<table file="GlobalSettingsTable.xsd"            name="GlobalSettingsTable"           entry="GlobalSettings"           enum="CommTypes.xsd"/>
<table file="IncomingGPRSTable.xsd"              name="IncomingGPRSTable"             entry="IncomingGPRS"             enum="CommTypes.xsd"/>
<table file="OutgoingGPRSTable.xsd"              name="OutgoingGPRSTable"             entry="OutgoingGPRS"             enum="CommTypes.xsd"/>
<table file="DefaultGPRSTable.xsd"               name="DefaultGPRSTable"              entry="DefaultGPRS"              enum="CommTypes.xsd"/>
<table file="ProxyTable.xsd"                     name="ProxyTable"                    entry="Proxy"                    enum="CommTypes.xsd"/>
<table file="LocationTable.xsd"                  name="LocationTable"                 entry="Location"                 enum="CommTypes.xsd"/>
<table file="SecureSocketTable.xsd"              name="SecureSocketTable"             entry="SecureSocket"             enum="CommTypes.xsd"/>
<table file="BTDeviceTable.xsd"                  name="BTDeviceTable"                 entry="BTDevice"                 enum="CommTypes.xsd"/>
<table file="BTPersistTable.xsd"                 name="BTPersistTable"                entry="BTPersist"                enum="CommTypes.xsd"/>
<table file="BTSecurityTable.xsd"                name="BTSecurityTable"               entry="BTSecurity"               enum="CommTypes.xsd"/>
<table file="BTDefaultTable.xsd"                 name="BTDefaultTable"                entry="BTDefault"                enum="CommTypes.xsd"/>
<table file="WAPAccessPointTable.xsd"            name="WAPAccessPointTable"           entry="WAPAccessPoint"           enum="CommTypes.xsd"/>
<table file="WAPIPBearerTable.xsd"               name="WAPIPBearerTable"              entry="WAPIPBearer"              enum="CommTypes.xsd"/>
<table file="WAPSMSBearerTable.xsd"              name="WAPSMSBearerTable"             entry="WAPSMSBearer"             enum="CommTypes.xsd"/>
<table file="VirtualBearerTable.xsd"             name="VirtualBearerTable"            entry="VirtualBearer"            enum="CommTypes.xsd"/>
<table file="VpnServiceTable.xsd"                name="VpnServiceTable"               entry="VpnService"               enum="CommTypes.xsd"/>
<table file="WLANServiceExtensionTable.xsd"      name="WLANServiceExtensionTable"     entry="WLANServiceExtension"     enum="CommTypes.xsd"/>
<table file="PANServiceExtensionsTable.xsd"      name="PANServiceExtensionsTable"     entry="PANServiceExtensions"     enum="CommTypes.xsd"/>
</CommDB:Contents>
